### PR TITLE
GAL-368 Fix FormattingXmlStreamWriter.writeStartElement(...) delegation

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/GAL-368

### CODE REVIEW

**Comment by jfdenise** [comment]
@pferraro , would you mind update the copyright year of the updated files? This is what breaks the CI. Thank-you.

**Comment by pferraro** [comment]
@jfdenise I'm confused.  Why would a bug fix require updating a copyright header?

**Comment by jfdenise** [comment]
@pferraro , galleon has some rules to update the copyright on file changes.

**Comment by jfdenise** [comment]
@pferraro , I created https://github.com/wildfly/galleon/pull/357 that contains your changes and copyright update.

**Pull request closed without merging**
