### PR TITLE
Fix for GAL-328, Update provisioning 3.0 xsd to reflect actual support

### PR DESCRIPTION
**Pull request by jfdenise**
* Added layers and config-deps to config
* Added origin and patches to feature-pack

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
@jfdenise is there no CI currently setup for PRs?

**Comment by jfdenise** [comment]
@aloubyansky , seems that travis.yml doesn't work anymore. I can see that ken opened a PR long time ago to add github action: https://github.com/wildfly/galleon/pull/289
Will see where we are here and will enable GH prior to merge this PR.

**Comment by aloubyansky** [comment]
Let's NOT use Travis anymore.

**Comment by jfdenise** [comment]
@aloubyansky FYI, checks passed.

**Comment by aloubyansky** [comment]
Thanks @jfdenise!

**Pull request merged**
